resolver: lts-15.3

packages:
  - beam-sqlite
  - beam-postgres
  - beam-core
  - beam-migrate
  - beam-migrate-cli

nix:
  shell-file: shell.nix

extra-deps:
  - constraints-extras-0.3.0.2
  - direct-sqlite-2.3.26
  - dependent-map-0.3
  - dependent-sum-0.6.2.0
  - sqlite-simple-0.4.18.0
